/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatsymGUI;

import chatsym.Chatsym;
import java.io.IOException;
import java.util.ArrayList;

/**
 *
 * @author Mateusz
 */
public class Opcje extends javax.swing.JFrame {

    /**
     * Creates new form Opcje
     */
    public Opcje() {
        initComponents();
    }

    int n;
    int odp;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dlugoscNgramu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dlugoscOdpowiedzi = new javax.swing.JTextField();
        opcjeZapisz = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        sciezkaPliku = new javax.swing.JTextField();
        wczytajTekstBazowy = new javax.swing.JButton();
        opcjeZamknij = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Długość n-gramu");

        jLabel2.setText("Długość odpowiedzi");

        dlugoscOdpowiedzi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlugoscOdpowiedziActionPerformed(evt);
            }
        });

        opcjeZapisz.setText("Zapisz");
        opcjeZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcjeZapiszActionPerformed(evt);
            }
        });

        jLabel3.setText("Ścieżka pliku bazowego");

        sciezkaPliku.setText("E:\\szkoła\\jimp2\\java\\przedwiosnie.txt");

        wczytajTekstBazowy.setText("Wczytaj tekst bazowy");
        wczytajTekstBazowy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wczytajTekstBazowyActionPerformed(evt);
            }
        });

        opcjeZamknij.setText("Zamknij okno");
        opcjeZamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcjeZamknijActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(wczytajTekstBazowy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(opcjeZamknij))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opcjeZapisz)
                            .addComponent(jLabel1)
                            .addComponent(dlugoscNgramu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(dlugoscOdpowiedzi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(sciezkaPliku, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dlugoscNgramu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dlugoscOdpowiedzi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(opcjeZapisz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sciezkaPliku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wczytajTekstBazowy)
                    .addComponent(opcjeZamknij))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcjeZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcjeZapiszActionPerformed
        n = Integer.parseInt(dlugoscNgramu.getText());
        odp = Integer.parseInt(dlugoscOdpowiedzi.getText());
        if (n > 1 && n < 6) {
            Okno.setNgram(n);
        }
        if (odp > 0 && odp < 100) {
            Okno.setOdpowiedz(odp);
        }
    }//GEN-LAST:event_opcjeZapiszActionPerformed

    private void dlugoscOdpowiedziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlugoscOdpowiedziActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dlugoscOdpowiedziActionPerformed

    private void wczytajTekstBazowyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wczytajTekstBazowyActionPerformed
        try {
            String tekstBazowy = Chatsym.readFile(sciezkaPliku.getText());
            String[] arr = tekstBazowy.split(" ");
            ArrayList<String> prefiks = new ArrayList<>();
            int size = arr.length;

            for (int i = 0; i < size - 2; i++) {
                prefiks.clear();
                prefiks.add(arr[i]);
                prefiks.add(arr[i + 1]);
                Okno.k.dodaj(prefiks, arr[i + 2]);
            }
        } catch (IOException e) {
            System.out.println("Podany plik nie działa");
        }

    }//GEN-LAST:event_wczytajTekstBazowyActionPerformed

    private void opcjeZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcjeZamknijActionPerformed
        dispose();
    }//GEN-LAST:event_opcjeZamknijActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opcje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opcje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opcje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opcje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opcje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dlugoscNgramu;
    private javax.swing.JTextField dlugoscOdpowiedzi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton opcjeZamknij;
    private javax.swing.JButton opcjeZapisz;
    private javax.swing.JTextField sciezkaPliku;
    private javax.swing.JButton wczytajTekstBazowy;
    // End of variables declaration//GEN-END:variables
}
